### ISSUE TITLE
Turn of Spotlight

### ISSUE THREAD

**Issue by bemrePG** [rock3r/uplift#2]
Hi, 

i am new in programming android and so far i try to understand the shadowing in android. 
I have seen you post on medium and you test app uplift.

Still i didn't get how i can turn of the "spot light" you were talking about.

Thanks you.

**Comment by rock3r** [comment]
You cannot turn it off, but you can set its alpha to zero. The article and the code tell you exactly what to do and where, but if those weren't enough, there's also a talk I did on the topic: https://speakerdeck.com/rock3r/uplift-material-shadows-on-android

In Android Q you will be able to do this at runtime much more easily by using [`HardwareRenderer#setLightSourceAlpha()`](https://developer.android.com/reference/android/graphics/HardwareRenderer.html#setLightSourceAlpha(float,%2520float)), but pre-Q you need theme hacks and all.
